### PR TITLE
Colorize expected and actual outputs

### PR DESCRIPTION
**Pull request by denisidoro**
| Before | After |
|:----:|:----:|
| before | after |

This uses https://github.com/greglook/puget

### Progress
- [x] Basic implementation
- [x] Some custom handlers
- [ ] Make sure output for fn, exceptions etc is ok
- [ ] Fix tests

### CODE REVIEW

**Comment by denisidoro** [comment]
I'm planning to toggle this feature through some config, because I understand some people may prefer a more simpler, minimalistic approach. WDYT?

**Comment by denisidoro** [comment]
Temporary closing without merging for inactivity

**Comment by denisidoro** [comment]
@phillipm, dou you think you can give me a hand to fix the broken tests?

**Comment by phillipm** [comment]
Hey @denisidoro, from what I can tell, it looks like the issue is that there are various tests that check the output of fact failures. They use regular expressions to do string comparisons, and when you colorize the failure output, this seems to cause the regular expressions to not match, due to 'hidden' ansi color characters.

I was able to get a few tests to pass using [this logic](https://github.com/AvisoNovate/pretty/blob/master/src/io/aviso/ansi.clj#L89-L94), which removes strips out the ansi color characters. For example, define the `strip-ansi` function in a test util file, and [wrap `@fact-output`](https://github.com/marick/Midje/blob/master/test/as_documentation/prerequisites/aaaaaa_the_basics.clj#L116) with it.

Also might want to make limited use of `lein midje :autotest` when applying these changes because it seems like there is a bug where colorization sometimes gets messed up on test re-runs, which makes it hard to debug the colorization test failures that need to be fixed in this PR :)

**Comment by phillipm** [comment]
@denisidoro I fixed the failing tests if you want to merge with upstream master and cherry-pick https://github.com/phillipm/Midje/commit/f606b2b0647e2d0a85d6d4c74e27998d84688cff into your branch, we can get this merged!

**Pull request closed without merging**
