### PR TITLE
Guarding against clojure.core/any?

### PR DESCRIPTION
**Pull request by bsvingen**
Guarding against any?, which is part of clojure.core in 1.9.

### CODE REVIEW

**Comment by benjyz** [comment]
I tried this, but the any warning still showed up at a bunch of places

```
lmt
WARNING: any? already refers to: #'clojure.core/any? in namespace: such.shorthand, being replaced by: #'such.shorthand/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: commons.clojure.core, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.emission.levels, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.util.pile, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.repl, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.emission.api, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.data.nested-facts, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.data.project-state, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.doc, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.other.arglists, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.emission.plugins.util, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.emission.plugins.default-failure-lines, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.1-to-explicit-form.metadata, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.util.recognizing, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.sweet, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkables, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.core, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.data.prerequisite-state, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.2-to-lexical-maps.fakes, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.lexical-maps, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.3-from-lexical-maps.from-fake-maps, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkers.chatty, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkers.util, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkers.simple, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkers.collection, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkers.collection-util, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.checking.checkers.collection-comparison, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.util.fnref, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.util.error-handling, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.1-to-explicit-form.parse-background, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.2-to-lexical-maps.expects, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.2-to-lexical-maps.data-fakes, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.util.laziness, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.0-to-fact-form.tabular, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.1-to-explicit-form.facts, being replaced by: #'commons.clojure.core/any?
WARNING: any? already refers to: #'clojure.core/any? in namespace: midje.parsing.0-to-fact-form.formulas, being replaced by: #'commons.clojure.core/any?
```

**Comment by bsvingen** [comment]
These warnings are fixed by [marick/suchwow/pull/4](https://github.com/marick/suchwow/pull/4) and [marick/clojure-commons/pull/1](https://github.com/marick/clojure-commons/pull/1).

**Comment by marick** [comment]
I was hoping that I could piggyback the changes on top of a new release of Potemkin, but it looks like not. I'll try to propagate fixes in the next couple of days.

**Comment by marick** [comment]
I think the just-created 1.9-alpha4 fixes this problem.

**Comment by bsvingen** [comment]
Confirmed. Thank you.

**Pull request merged**
