### PR TITLE
Colorize expected and actual outputs

### PR DESCRIPTION
**Pull request by phillipm**
Version of @denisidoro's PR https://github.com/marick/Midje/pull/382 with tests adapted to disregard ANSI text coloring codes

### CODE REVIEW

**Comment by denisidoro** [comment]
🚢 ?

**Comment by phillipm** [comment]
I'm going to merge this now and do an alpha release so everyone can get to using this. I'll soon follow up with a PR that allows you to turn off this functionality in case you prefer non-pretty printed output (just like in requested for this PR https://github.com/marick/Midje/pull/402#issuecomment-327527547)

**Comment by pjlegato** [comment]
This looks great! Would it be possible to get something similar for the output of `Checking function:`, `Best match found:`, and `It matched:`?

**Comment by pjlegato** [comment]
Even more awesome would be if it could do a diff on expected versus actual, and highlight the parts that differed somehow.... I often have complex nested maps as checker results, which currently have to be sifted through manually. That'd be a huge timesaver.

**Pull request merged**
