### PR TITLE
Fix #321 by recreating the tools.namespace records before using them

### LINKED ISSUE #321: Midje autotest fails when ring.middleware.reload library and :reload-all flag are used together
Hi,

I'm using Mac OS X and Clojure 1.7.

Midje autotest has stopped working for me for a week. I've tried the lein flag and the repl command. I've also them it in iTerm and Terminal.

It used to work almost as expected until a week ago. By almost what I mean is when I chanced a line in a file it didn't react from time to time. Now it doesn't react even I put new files or make huge changes.

I'm getting a lot of reflection warnings, could these help spotting the issue?

### PR DESCRIPTION
**Pull request by dlebrero**
The :reload-all causes the tools.namespace protocols to be reloaded, which causes:

java.lang.IllegalArgumentException: No implementation of method: :nodes of protocol: #'clojure.tools.namespace.dependency/DependencyGraph found for class: clojure.tools.namespace.dependency.MapDependencyGraph
  at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
  at clojure.tools.namespace.dependency$eval24795$fn__24848$G__24786__24853.invoke(dependency.clj:14)
  at clojure.tools.namespace.track$remove.invoke(track.clj:97)
  at clojure.tools.namespace.file$remove_files.invoke(file.clj:63)
  at clojure.tools.namespace.dir$update_files.invoke(dir.clj:38)
  at clojure.tools.namespace.dir$scan_all.doInvoke(dir.clj:73)
  at clojure.lang.RestFn.applyTo(RestFn.java:139)
  at clojure.core$apply.invoke(core.clj:632)
  at midje.data.project_state$mkfn_COLON_scan_and_react$fn__24132$fn__24133.invoke(project_state.clj:142)
  at clojure.lang.Atom.swap(Atom.java:37)
  at clojure.core$swap_BANG_.invoke(core.clj:2238)
  at midje.data.project_state$mkfn_COLON_scan_and_react$fn__24132.invoke(project_state.clj:141)
  at midje.data.project_state$load_everything.invoke(project_state.clj:151)

To fix the issue, the tools.namespace MapDependencyGraph record held in the state tracker needs to be recreated before using it

### CODE REVIEW

**Comment by marick** [comment]
I saw the same problem you did, so I merged the pull request. However, I now get an immediate:
```
crede.core=> (autotest)
Because failures in the initial load break autotest's dependency tracking,
autotest has been cancelled.
true
```

Investigating...

**Comment by dlebrero** [comment]
which project are you running? I tested it with the #321

**Comment by marick** [comment]
I can reproduce by cloning https://github.com/marick/sample-midje-project and making this change in `project.clj`:

```clojure
  :profiles {:dev {:dependencies [[midje "1.9.0-SNAPSHOT"]]
```
... then doing this:

```
667 $ lein repl
nREPL server started on port 64344 on host 127.0.0.1 - nrepl://127.0.0.1:64344
REPL-y 0.3.7, nREPL 0.2.10
Clojure 1.7.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (use 'midje.repl)
This is from the Midje configuration file in ${HOME}.
You can change the configuration independently for the repl.
Run `(doc midje)` for Midje usage.
Run `(doc midje-repl)` for descriptions of Midje repl functions.
nil
user=> (autotest)
Because failures in the initial load break autotest's dependency tracking,
autotest has been cancelled.
true
```

**Comment by dlebrero** [comment]
I see a NPE. To fix:

(defn with-fresh-copy-of-dependency-map
  "Records must be recreated if the protocols that they implement are reloaded."
  [state]
  (if (get state deps-key)
    (update-in state [deps-key] clojure.tools.namespace.dependency/map->MapDependencyGraph)
    state))

Let me know if you prefer a pull request

**Comment by marick** [comment]
That's helped so far - I'll let you know if I detect any other problems.

**Pull request merged**
